name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Set +x for *.ps1
        run: chmod +x ps/*.ps1
      - name: Setting up dotnet 8 as default SDK
        run: |
          dotnet new globaljson --sdk-version 8.0.0 --roll-forward minor
          dotnet --version
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' 
      - name: Install SonarCloud scanner
        run: dotnet tool install --global dotnet-sonarscanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"ku3mich_Xunit.Include" /o:"ku3mich" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
          dotnet build --configuration Release
          ./ps/run-tests.ps1
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      - name: Pack nugets
        working-directory: ./ps
        run: ./run-pack.ps1
      - name: Push-nugets
        env:
            NUGET_FEED: https://api.nuget.org/v3/index.json
            NUGET_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
        working-directory: ./ps
        run: ./run-push.ps1

